### PR TITLE
Align snake option to others that require -d (directory)

### PR DESCRIPTION
**Pull request by pix303**
-snake proposed as a bool
move as first check directory existence

go.mod and go.sum was updated, but don't know why and how happen... :/

### CODE REVIEW

**Comment by guerinoni** [comment]
@pix303 
Thanks for PR...
These 2 files are update maybe because you hit something like `go get -u all` this update all pkg used in the project! We can do this in a different PR
For rest of the code seems ok but fix lint errors :)

**Comment by guerinoni** [comment]
@pix303 
Seems good! Can I ask the last 2 things...?
1. Remove commit "go.mod updated" because I update all module in separated PR
2. Edit commit message in order to align with other (capitalize, present verb... old but gold post https://chris.beams.io/posts/git-commit/)

**Comment by pix303** [comment]
Sorry... delay because of new work/new pc to set but most of all i can't figure out **labeler problem**...
About go.mod go.sum i've reset with older ones.

**Comment by guerinoni** [comment]
@pix303 on my PR it works, I don't know but for now is not a problem!

**Review by guerinoni — CHANGES_REQUESTED** [review]
Seems all good! 
Rewrite history of commit message and remove update of dependecies, then I will merge it!

**Comment by pix303** [comment]
Check it out the new commit history. Still remain error on PR label because i can't figure out how to fix :/

**Review by guerinoni — APPROVED** [review]

**Pull request merged**
